backend:
  name: git-gateway
  branch: main #

media_folder: "public/uploads"
public_folder: "https://construtoraconfidence.com/"
show_preview_links: false
logo_url: https://www.construtoraconfidence.com/favicon.png
media_library:
  name: uploadcare
  
collections:
  - name: "logo_content_left"
    label: "Conteúdo de texto da landing logo à esquerda"
    folder: "public/static_content/"
    create: true
    slug: "logo-landing-content-left"
    fields:
      - {label: "Content", name: "mdsession", widget: "markdown", required: true}

  - name: "logo_content_right"
    label: "Conteúdo de texto da landing logo à direita"
    folder: "public/static_content/"
    create: true
    slug: "logo-landing-content-right"
    fields:
      - {label: "Content", name: "mdsession", widget: "markdown", required: true}
  
  - name: "empresa_welcome"
    label: "Welcome Message"
    folder: "public/static_content/"
    create: true
    slug: "empresa_welcome"
    fields:
      - {label: "Content", name: "mdsession", widget: "markdown", required: true}

  - name: "followup"
    label: "Welcome Message followup"
    folder: "public/static_content/"
    create: true
    slug: "followup"
    fields:
      - {label: "Content", name: "mdsession", widget: "markdown", required: true}
  
  
      
  - name: "portfolio_items" # Used in routes, e.g., /admin/collections/sections
    label: "Sessão de portfólio" # Used in the UI
    format: json
    public_folder: 'https://construtoraconfidence.com/uploads'
    folder: "public/portfolio_items/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{fields.titulo}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      #- {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Título", name: "titulo", widget: "string"}
      - label: "Galeria de Sessões"
        name: "sessions"
        widget: "list"
        allow_add: true
        fields: 
          - {label: "Foto", name: "foto", widget: "file"}
          - {label: "Título", name: "titulo", widget: "string", required: false}
          - {label: "Descrição curta", name: "shortstory", widget: "text", required: false}
          - {label: "Descrição longa", name: "tailstory", widget: "text", required: false}
          - {label: "MD Session", name: "mdsession", widget: "markdown", required: false}
              
      - label: "Story"
        name: story
        widget: "object"
        fields:
          - {label: "Descrição curta", name: "twitterlike", widget: "text"}
          - {label: "Descrição longa", name: "2paraph", widget: "markdown"}